KUBEFLOW_ENDPOINT: http://localhost:8080
KUBEFLOW_USERNAME: user@example.com
KUBEFLOW_PASSWORD: '12341234'
REMOTE_CSC_CLUSTER_SSH_PRIVATE_KEY: ''
REMOTE_CSC_CLUSTER_SSH_IP: ''
REMOTE_CSC_CLUSTER_SSH_USERNAME: ''
